apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: site
        image: aluizsys/conversao-temperatura:latest
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-service
spec:
  selector:
    app: converter
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30000
  type: NodePort
